"""add ai ranking and property search ranking models

Revision ID: 19b4b99542b4
Revises: 1e0717aeb849
Create Date: 2026-04-13 13:48:12.352145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b4b99542b4'
down_revision: Union[str, Sequence[str], None] = '1e0717aeb849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('semantic_score_weight', sa.Float(), nullable=False),
    sa.Column('price_score_weight', sa.Float(), nullable=False),
    sa.Column('location_score_weight', sa.Float(), nullable=False),
    sa.Column('recency_score_weight', sa.Float(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('reranker_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('bias_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('explanation_helpful', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_feedback_session_id'), 'search_feedback', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_feedback_session_id'), table_name='search_feedback')
    op.drop_table('search_feedback')
    op.drop_table('admin_audit_logs')
    op.drop_table('search_logs')
    op.drop_table('ranking_config')
    # ### end Alembic commands ###
